# Peter Thornton, 17 Feb 18
# Even Fibonacci numbers
# https://projecteuler.net/problem=2

# Problem Statement

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.


"""This function sums Even Fibonacci numbers."""
i = 0
j = 1
x = 0
z = 4000000

# Set End point
print("This function sums Even Fibonacci numbers for your selected end-point or is preset 4000000.")
if input("Would you like to input an end-point (Y/N): ") == "Y":
    z = int(input("Please enter an integer: "))

while i <= z:
    if i % 2 == 0: 
        x += i
    i, j = j, i + j
    
print("The sum of the Even Fibonacci numbers for", z,"is:",x)
